galaxy_info:
  author: Emilien Kenler <ekenler@wizcorp.jp>
  description: Manage the iptables rules.
  company: Wizcorp K.K.
  license: MIT
  min_ansible_version: 1.8.1
  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - all
  categories:
    - system
    - networking
dependencies:
  - role: AerisCloud.yum
