---

- name: install apache webserver
  when: ansible_os_family == 'Debian'
  apt: name=apache2 state=installed

- name: ensure webserver is started
  when: ansible_os_family == 'Debian'
  service: name=apache2 state=started

- name: install apache webserver
  when: ansible_os_family == 'RedHat'
  yum: name=httpd state=installed

- name: ensure webserver is started
  when: ansible_os_family == 'RedHat'
  service: name=httpd state=started


- name: deploy home page
  template: src=index.j2 dest={{ doc_root }}/index.html
  notify:
  - restart_webserver

- include: user.yml
